/*
for i in 1 -> 100 {
	if i % 5 == 0 and i % 3 == 0:	print "fizzbuzz"
	else if i % 5 == 0:		print "fizz"
	else if i % 3 == 0:		print "buzz"
	else				print i
}
*/

fn fizzbuzz = {
	for var i = 1; i < 101; i++ {
		if i % 5 == 0 and i % 3 == 0:	print "fizzbuzz"
		else if i % 5 == 0:		print "fizz"
		else if i % 3 == 0:		print "buzz"
		else				print i
	}
}

-f(a = -85 * 92 - 23 ? b++ = (25 * (22 + 38)) : --c = 63) * 43;
fizzbuzz(1, 2, 3)
fizzbuzz(4, 5, 6)
#(fizzbuzz * 2)(1, 2, 3), 2 * 5
